### ISSUE TITLE
Tracks do not belong to users

### ISSUE THREAD

**Issue by andrewhamon** [partygoer/partygoer-api#1]
Ideally there would be guest users (implemented using sessions/cookies) as well as authenticated users, and the ability to convert a guest to an authenticated user. Track could belong to guest user or full user with [polymorphic associations] (http://guides.rubyonrails.org/association_basics.html#polymorphic-associations).

**Comment by stevenpetryk** [comment]
Fixed by c39e97aaf8eba94f466f22eee208a918e53a393a
