### ISSUE TITLE
Faye messages can be published by anyone

### ISSUE THREAD

**Issue by andrewhamon** [partygoer/partygoer-api#10]
We're currently using a server-push model. So any messages from clients to server should just be done using normal, restful HTTP requests. But a malicious user can, currently, broadcast messages to all who are subscribed. This is basically as close to letting anyone write whatever they wanted to the database as we can get without actually letting them, since messages on faye are currently trusted by clients as if they came from the database.

Again, this could be an easy fix with a shared key between the faye and rails servers (probably in an environment variable) and a faye extension that only allows publishing with a valid key.

**Comment by stevenpetryk** [comment]
[Relevant article on Faye's website](http://faye.jcoglan.com/security/publication.html)

**Comment by andrewhamon** [comment]
Fixed by 22abd7f930994dcec49551c72a45674c1b5cd98e
