### ISSUE TITLE
faye.ru does not load .env automatically in development

### ISSUE THREAD

**Issue by andrewhamon** [partygoer/partygoer-api#16]

**Comment by andrewhamon** [comment]
In the meantime you can invoke faye using `dotenv rackup faye.ru -s thin -E production`

**Comment by stevenpetryk** [comment]
Can you not use dotenv inside of a rack application? It doesn't load automatically in the Rails app either.

**Comment by andrewhamon** [comment]
It should be loading automatically in the rails app if the rails environment is development according to [the dotenv readme](https://github.com/bkeepers/dotenv#rails).

In a non-rails code, though, you need to [do this](https://github.com/bkeepers/dotenv#sinatra-or-plain-ol-ruby).

So i just need to put that in a guard clause that checks if RAILS_ENV is development or null.
