### ISSUE TITLE
Does not support multiple parties/rooms

### ISSUE THREAD

**Issue by andrewhamon** [partygoer/partygoer-api#2]
Currently, the api only supports a single "party" or "room." Ideally, users can create a new party that would be found at partyname.example.com, and the root example.com might point to a splash page with a list of the most hoping parties/information about partygoer, etc.

A party would belong to a user (preferably only an authenticated user), and that user might have special privileges for that room, such as removing tracks and banning users.

**Comment by stevenpetryk** [comment]
What should be the attributes for a party? Here are some ideas:

* Name (to be shown to party members)
* URI (could be optional)
* LatLong
* Geofence radius

**Comment by andrewhamon** [comment]
Also:
- Duration (expiration)
- Owner

**Comment by stevenpetryk** [comment]
I think duration could just be `expires_at`

**Comment by stevenpetryk** [comment]
Final list for now:

* `name`
* `uri`
* `latitude`
* `longitude`
* `geofence_radius`
* `expires_at`
* `user` (belongs to)
