### ISSUE TITLE
Use integer instead of boolean value for Vote

### ISSUE THREAD

**Issue by andrewhamon** [partygoer/partygoer-api#20]
Currently, Vote is a boolean where we interpret true as "upvote" and false as "downvote."

In order to find the total score for a track, currently two separate queries are run: counting the upvotes, then counting the downvotes: `votes.where(up: true).count - votes.where(up: false).count`

If instead we used integers (there +1 is up and -1 is down) then we could simply use sum, which would perform better and result in more expressive code `votes.sum(:up)`

Sum should perform better as it would only result in one scan.

**Comment by andrewhamon** [comment]
Fixed with 1960fe38084a7cc3b8ce4d63bc6e15fafbe1900b (and for bonus it uses an Enum!)

**Comment by stevenpetryk** [comment]
This is now implemented in the UI by 70d6e3b00a8dbf190c3edda91c99ea5922e4b82b.
