### ISSUE TITLE
Every realtime object should include its realtime channel as a (virtual?) attribute

### ISSUE THREAD

**Issue by stevenpetryk** [partygoer/partygoer-api#22]
To allow the frontend to be even more implementation-agnostic, it would be nice to have every realtime object (i.e. tracks and parties) store the location of its realtime channel.

Even better may be to assign each party and track a UUID, and manage pubsub events via the UUID (instead of the database ID). This would prevent attackers from subscribing to arbitrary objects.

**Comment by andrewhamon** [comment]
Most of the groundwork has been laid for this. Unfortunately I did it in the karma branch.

**Comment by andrewhamon** [comment]
Fixed in 04c878eda5f84b00 and now merged in to master
