### ISSUE TITLE
Should posting to faye even be a job?

### ISSUE THREAD

**Issue by andrewhamon** [partygoer/partygoer-api#27]
Since we decided we would prefer to run it inline I think it would make more sense for that functionality to belong to ApplicationController.

My only concern then is that failure to post would either need to be caught and logged or would result in a 500 error. Considering that faye is pretty crucial to our app I don't think job failures should merely be silenced.

Thoughts @stevenpetryk?

**Comment by stevenpetryk** [comment]
We should just make it inline, and allow the exception to bubble up and become a 500 error. I can handle it "gracefully" in the UI by telling the user that the app is currently experiencing trouble (or something). In production I'm assuming we'll use one of those services that notifies you of exceptions in your app.
