### ISSUE TITLE
Optionally blocking explicit songs?

### ISSUE THREAD

**Issue by stevenpetryk** [partygoer/partygoer-api#32]
People who are hosting public parties and who are expecting a lot of participation may want the ability to block explicit songs. Spotify includes an `explicit` parameter on all of the tracks it returns. This may be a handy feature.

**Comment by stevenpetryk** [comment]
Mockup of what the setting would look like: https://github.com/partygoer/partygoer-web/issues/6#issuecomment-107056716

**Comment by andrewhamon** [comment]
No.
