### ISSUE TITLE
Adding first track (after boot) very slow

### ISSUE THREAD

**Issue by andrewhamon** [partygoer/partygoer-api#5]
Possibly due to lazy loading of RSpotify and its dependencies. Since RSpotify is only used for validating the URI perhaps the Spotify WEB API should just be used directly.

**Comment by stevenpetryk** [comment]
I believe this was fixed by 466b478412e29566ed5526d3290de0e3345b6ebf. Reopen if not.

**Comment by stevenpetryk** [comment]
Just noticed the delay again.

**Comment by andrewhamon** [comment]
No, I didn't add the change yet

On Mar 6, 2015, at 8:36 AM, Steven Petryk <notifications@github.com> wrote:

Just noticed the delay again.

—
Reply to this email directly or view it on GitHub
<https://github.com/partygoer/partygoer-api/issues/5#issuecomment-77559132>.

**Comment by andrewhamon** [comment]
The issue was determined to be caused by the system DNS lookup in the virtual machine, which explained why it wasn't slow on the server. There was a fix in the form of using a the ruby DNS implementation, but ultimately I left that out since only the vagrant VM was affected.

Additionally, 437e5ad46da051bc154235e0d261e67e58e50a3d stubs out the Spotify requests in most of the tests.
