### ISSUE TITLE
Builds failing due to Faye requests

### ISSUE THREAD

**Issue by stevenpetryk** [partygoer/partygoer-api#7]
Travis CI is reporting failures because the server is attempting to send messages over the network to http://localhost:3000. Either travis should be configured to start a Faye server, or we should abstract Faye messaging into a method that simply noop's in test mode.

**Comment by andrewhamon** [comment]
(Sort of) Fixed by bf1ab3b1ac0484088aee9a8ca77ab6b3fd672599

Exceptions thrown when trying to post to faye are now caught wholesale. Shitty fix, but whatever.
